// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertInfoController from "./alert_info_controller.js"
application.register("alert-info", AlertInfoController)

import DropdownController from "./dropdown_controller.js"
application.register("dropdown", DropdownController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)
