version: '1'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bin/rails server -b 0.0.0.0
    ports:
      - '5000:3000'
    links:
      - db
    volumes:
      - ./app:cache
  db:
    image: nouchka/sqlite3:latest
    restart: always
    ports:
      - '89:89'
    volumes:
      - ./sqlite3:/docker-entrypoint-initdb.d
networks:
  default:
